<a href="https://colab.research.google.com/github/HausReport/ClubRaiders/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
from typing import List
from datetime import datetime
from random import randint
from dateutil.relativedelta import *

In [12]:
    factionName: List[str] = []
    systemName: List[str] = []
    population: List[int] = []
    influence: List[float] = []
    updated: List[datetime] = []

In [47]:
factionName: List[str] = []
systemName: List[str] = []
population: List[int] = []
influence: List[float] = []
updated: List[datetime] = []
    
randStrs = ['foo', 'bar', 'guh']

def randStr() -> str:
  global randStrs
  return randStrs[randint(0, len(randStrs))]

def seqStr(i: int) -> str:
  global randStrs
  return randStrs[i % len(randStrs)]

start_date = datetime.strptime("2020-06-01", "%Y-%m-%d")


for fac in ['foo','bar','guh']:
  upd = start_date
  for sys in ['sol','celeano']:
    for i in range(0,5):
      factionName.append( fac)
      systemName.append( sys)
      population.append(10000)
      influence.append(.33)

      day = randint(2,4)
      upd = upd + relativedelta(hours=day*8)
      updated.append(upd)


data = { 'systemName' : systemName,
         'factionName' : factionName,
         'population' : population,
         'influence'  : influence,
         'updated' : updated
        }
df = pd.DataFrame(data = data)
df['updated'] = df.updated.dt.round("D") 
df = df.sort_values(by=['systemName', 'factionName','updated'])
df['diff1'] = df.updated.diff(periods=1).dt.days
df['diff2'] = df.updated.diff(periods=-1).dt.days



df

   systemName factionName  population  influence    updated  diff1  diff2
15    celeano         bar       10000       0.33 2020-06-07    NaN    0.0
16    celeano         bar       10000       0.33 2020-06-07    0.0   -2.0
17    celeano         bar       10000       0.33 2020-06-09    2.0   -1.0
18    celeano         bar       10000       0.33 2020-06-10    1.0   -1.0
19    celeano         bar       10000       0.33 2020-06-11    1.0    4.0
5     celeano         foo       10000       0.33 2020-06-07   -4.0   -1.0
6     celeano         foo       10000       0.33 2020-06-08    1.0   -1.0
7     celeano         foo       10000       0.33 2020-06-09    1.0   -1.0
8     celeano         foo       10000       0.33 2020-06-10    1.0   -1.0
9     celeano         foo       10000       0.33 2020-06-11    1.0    3.0
25    celeano         guh       10000       0.33 2020-06-08   -3.0   -1.0
26    celeano         guh       10000       0.33 2020-06-09    1.0   -1.0
27    celeano         guh       10000       0.33 2020-06-10    1.0   -2.0
28    celeano         guh       10000       0.33 2020-06-12    2.0   -1.0
29    celeano         guh       10000       0.33 2020-06-13    1.0   11.0
10        sol         bar       10000       0.33 2020-06-02  -11.0   -1.0
11        sol         bar       10000       0.33 2020-06-03    1.0   -1.0
12        sol         bar       10000       0.33 2020-06-04    1.0   -1.0
13        sol         bar       10000       0.33 2020-06-05    1.0   -1.0
14        sol         bar       10000       0.33 2020-06-06    1.0    4.0
0         sol         foo       10000       0.33 2020-06-02   -4.0   -1.0
1         sol         foo       10000       0.33 2020-06-03    1.0   -1.0
2         sol         foo       10000       0.33 2020-06-04    1.0   -1.0
3         sol         foo       10000       0.33 2020-06-05    1.0   -1.0
4         sol         foo       10000       0.33 2020-06-06    1.0    4.0
20        sol         guh       10000       0.33 2020-06-02   -4.0   -2.0
21        sol         guh       10000       0.33 2020-06-04    2.0   -1.0
22        sol         guh       10000       0.33 2020-06-05    1.0   -1.0
23        sol         guh       10000       0.33 2020-06-06    1.0   -1.0
24        sol         guh       10000       0.33 2020-06-07    1.0    NaN

In [7]:
df: pd.DataFrame